export const productList = [{
    "name": "Oranges",
    "description": "Oranges",
    "category": "fruits",
    "unitPrice": "2.49",
    "unitQuantity": "1",
    "unit": "lb",
    "imgUrl": "https://storage.googleapis.com/atkurb/oranges.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e78"
}, {
    "name": "Papaya",
    "description": "Papaya",
    "category": "fruits",
    "unitPrice": "2.49",
    "unitQuantity": "1",
    "unit": "ct",
    "imgUrl": "https://storage.googleapis.com/atkurb/papaya.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e79"
}, {
    "name": "Passion Fruit",
    "description": "Passion Fruit",
    "category": "fruits",
    "unitPrice": "1.99",
    "unitQuantity": "1",
    "unit": "ct",
    "imgUrl": "https://storage.googleapis.com/atkurb/passionFruit.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e7a"
}, {
    "name": "Peaches",
    "description": "Peaches",
    "category": "fruits",
    "unitPrice": "2.49",
    "unitQuantity": "1",
    "unit": "lb",
    "imgUrl": "https://storage.googleapis.com/atkurb/peaches.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e7b"
}, {
    "name": "Pears",
    "description": "Pears",
    "category": "fruits",
    "unitPrice": "4.99",
    "unitQuantity": "1",
    "unit": "lb",
    "imgUrl": "https://storage.googleapis.com/atkurb/pears.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e7c"
}, {
    "name": "Persimmons",
    "description": "Persimmons",
    "category": "fruits",
    "unitPrice": "4.99",
    "unitQuantity": "1",
    "unit": "lb",
    "imgUrl": "https://storage.googleapis.com/atkurb/persimmons.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e7d"
}, {
    "name": "Pineapple",
    "description": "Pineapple",
    "category": "fruits",
    "unitPrice": "2.49",
    "unitQuantity": "1",
    "unit": "ct",
    "imgUrl": "https://storage.googleapis.com/atkurb/pineapple.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e7e"
}, {
    "name": "Plantains",
    "description": "Plantains",
    "category": "fruits",
    "unitPrice": "2.49",
    "unitQuantity": "1",
    "unit": "lb",
    "imgUrl": "https://storage.googleapis.com/atkurb/plantains.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e7f"
}, {
    "name": "Plum",
    "description": "Plum",
    "category": "fruits",
    "unitPrice": "3.49",
    "unitQuantity": "1",
    "unit": "lb",
    "imgUrl": "https://storage.googleapis.com/atkurb/plum.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e80"
}, {
    "name": "Pomegranate",
    "description": "Pomegranate",
    "category": "fruits",
    "unitPrice": "2.49",
    "unitQuantity": "1",
    "unit": "ct",
    "imgUrl": "https://storage.googleapis.com/atkurb/pomegranate.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e81"
}, {
    "name": "Potatoes",
    "description": "Potatoes",
    "category": "vegetables",
    "unitPrice": "2.49",
    "unitQuantity": "1",
    "unit": "lb",
    "imgUrl": "https://storage.googleapis.com/atkurb/potatoes.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e82"
}, {
    "name": "Pumpkin",
    "description": "Pumpkin",
    "category": "vegetables",
    "unitPrice": "4.49",
    "unitQuantity": "1",
    "unit": "ct",
    "imgUrl": "https://storage.googleapis.com/atkurb/pumpkin.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e83"
}, {
    "name": "Radishes",
    "description": "Radishes",
    "category": "vegetables",
    "unitPrice": "2.49",
    "unitQuantity": "1",
    "unit": "lb",
    "imgUrl": "https://storage.googleapis.com/atkurb/radishes.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e84"
}, {
    "name": "Raspberries",
    "description": "Raspberries",
    "category": "fruits",
    "unitPrice": "6.49",
    "unitQuantity": "1",
    "unit": "lb",
    "imgUrl": "https://storage.googleapis.com/atkurb/raspberries.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e85"
}, {
    "name": "Red Cabbage",
    "description": "Red Cabbage",
    "category": "vegetables",
    "unitPrice": "2.29",
    "unitQuantity": "1",
    "unit": "ct",
    "imgUrl": "https://storage.googleapis.com/atkurb/redCabbage.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e86"
}, {
    "name": "Red Grapes",
    "description": "Red Grapes",
    "category": "fruits",
    "unitPrice": "2.49",
    "unitQuantity": "1",
    "unit": "lb",
    "imgUrl": "https://storage.googleapis.com/atkurb/redGrapes.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e87"
}, {
    "name": "Red Onions",
    "description": "Red Onions",
    "category": "vegetables",
    "unitPrice": "2.49",
    "unitQuantity": "1",
    "unit": "lb",
    "imgUrl": "https://storage.googleapis.com/atkurb/redOnions.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e88"
}, {
    "name": "Romaine Lettuce",
    "description": "Romaine Lettuce",
    "category": "vegetables",
    "unitPrice": "1.99",
    "unitQuantity": "1",
    "unit": "ct",
    "imgUrl": "https://storage.googleapis.com/atkurb/romaineLettuce.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e89"
}, {
    "name": "Shallots",
    "description": "Shallots",
    "category": "vegetables",
    "unitPrice": "1.99",
    "unitQuantity": "1",
    "unit": "lb",
    "imgUrl": "https://storage.googleapis.com/atkurb/shallots.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e8a"
}, {
    "name": "Spinach",
    "description": "Spinach",
    "category": "vegetables",
    "unitPrice": "1.99",
    "unitQuantity": "1",
    "unit": "ct",
    "imgUrl": "https://storage.googleapis.com/atkurb/spinach.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e8b"
}, {
    "name": "Squash",
    "description": "Squash",
    "category": "vegetables",
    "unitPrice": "2.99",
    "unitQuantity": "1",
    "unit": "lb",
    "imgUrl": "https://storage.googleapis.com/atkurb/squash.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e8c"
}, {
    "name": "Strawberries",
    "description": "Strawberries",
    "category": "fruits",
    "unitPrice": "4.99",
    "unitQuantity": "1",
    "unit": "lb",
    "imgUrl": "https://storage.googleapis.com/atkurb/strawberries.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e8d"
}, {
    "name": "Sweet Potato",
    "description": "Sweet Potato",
    "category": "vegetables",
    "unitPrice": "2.99",
    "unitQuantity": "1",
    "unit": "lb",
    "imgUrl": "https://storage.googleapis.com/atkurb/sweetPotato.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e8e"
}, {
    "name": "Tangerines",
    "description": "Tangerines",
    "category": "fruits",
    "unitPrice": "1.99",
    "unitQuantity": "1",
    "unit": "lb",
    "imgUrl": "https://storage.googleapis.com/atkurb/tangerines.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e8f"
}, {
    "name": "Tomatoes",
    "description": "Tomatoes",
    "category": "vegetables",
    "unitPrice": "1.99",
    "unitQuantity": "1",
    "unit": "lb",
    "imgUrl": "https://storage.googleapis.com/atkurb/tomatoes.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e90"
}, {
    "name": "Turnips",
    "description": "Turnips",
    "category": "vegetables",
    "unitPrice": "1.99",
    "unitQuantity": "1",
    "unit": "lb",
    "imgUrl": "https://storage.googleapis.com/atkurb/turnips.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e91"
}, {
    "name": "Watercress",
    "description": "Watercress",
    "category": "vegetables",
    "unitPrice": "3.99",
    "unitQuantity": "1",
    "unit": "ct",
    "imgUrl": "https://storage.googleapis.com/atkurb/watercress.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e92"
}, {
    "name": "Watermelon",
    "description": "Watermelon",
    "category": "fruits",
    "unitPrice": "3.49",
    "unitQuantity": "1",
    "unit": "ct",
    "imgUrl": "https://storage.googleapis.com/atkurb/watermelon.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e93"
}, {
    "name": "White Onions",
    "description": "White Onions",
    "category": "vegetables",
    "unitPrice": "2.49",
    "unitQuantity": "1",
    "unit": "lb",
    "imgUrl": "https://storage.googleapis.com/atkurb/whiteOnions.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e94"
}, {
    "name": "Yellow Onions",
    "description": "Yellow Onions",
    "category": "vegetables",
    "unitPrice": "2.49",
    "unitQuantity": "1",
    "unit": "lb",
    "imgUrl": "https://storage.googleapis.com/atkurb/yellowOnions.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e95"
}, {
    "name": "Zucchini",
    "description": "Zucchini",
    "category": "vegetables",
    "unitPrice": "1.49",
    "unitQuantity": "1",
    "unit": "ct",
    "imgUrl": "https://storage.googleapis.com/atkurb/zucchini.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e96"
}, {
    "name": "Apple",
    "description": "Apple",
    "category": "fruits",
    "unitPrice": "4.49",
    "unitQuantity": "1",
    "unit": "lb",
    "imgUrl": "https://storage.googleapis.com/atkurb/apple.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e49"
}, {
    "name": "Apricots",
    "description": "Apricots",
    "category": "fruits",
    "unitPrice": "6.49",
    "unitQuantity": "1",
    "unit": "lb",
    "imgUrl": "https://storage.googleapis.com/atkurb/apricots.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e4a"
}, {
    "name": "Artichoke",
    "description": "Artichoke",
    "category": "vegetables",
    "unitPrice": "2.99",
    "unitQuantity": "1",
    "unit": "lb",
    "imgUrl": "https://storage.googleapis.com/atkurb/artichoke.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e4b"
}, {
    "name": "Asparagus",
    "description": "Asparagus",
    "category": "vegetables",
    "unitPrice": "1.49",
    "unitQuantity": "1",
    "unit": "lb",
    "imgUrl": "https://storage.googleapis.com/atkurb/asparagus.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e4c"
}, {
    "name": "Avocados",
    "description": "Avocados",
    "category": "fruits",
    "unitPrice": "3.49",
    "unitQuantity": "1",
    "unit": "ct",
    "imgUrl": "https://storage.googleapis.com/atkurb/avocados.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e4d"
}, {
    "name": "Bamboo Shoots",
    "description": "Bamboo Shoots",
    "category": "vegetables",
    "unitPrice": "2.49",
    "unitQuantity": "1",
    "unit": "lb",
    "imgUrl": "https://storage.googleapis.com/atkurb/bambooShoots.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e4e"
}, {
    "name": "Bananas",
    "description": "Bananas",
    "category": "fruits",
    "unitPrice": "1.49",
    "unitQuantity": "1",
    "unit": "lb",
    "imgUrl": "https://storage.googleapis.com/atkurb/bananas.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e4f"
}, {
    "name": "Beetroot",
    "description": "Beetroot",
    "category": "vegetables",
    "unitPrice": "3.49",
    "unitQuantity": "1",
    "unit": "lb",
    "imgUrl": "https://storage.googleapis.com/atkurb/beetroot.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e50"
}, {
    "name": "Black Grapes",
    "description": "Black Grapes",
    "category": "fruits",
    "unitPrice": "3.49",
    "unitQuantity": "1",
    "unit": "lb",
    "imgUrl": "https://storage.googleapis.com/atkurb/blackGrapes.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e51"
}, {
    "name": "Blackberries",
    "description": "Blackberries",
    "category": "fruits",
    "unitPrice": "3.49",
    "unitQuantity": "1",
    "unit": "lb",
    "imgUrl": "https://storage.googleapis.com/atkurb/blackberries.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e52"
}, {
    "name": "Blueberries",
    "description": "Blueberries",
    "category": "fruits",
    "unitPrice": "3.49",
    "unitQuantity": "1",
    "unit": "lb",
    "imgUrl": "https://storage.googleapis.com/atkurb/blueberries.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e53"
}, {
    "name": "Bok Choy",
    "description": "Bok Choy",
    "category": "vegetables",
    "unitPrice": "3.49",
    "unitQuantity": "1",
    "unit": "lb",
    "imgUrl": "https://storage.googleapis.com/atkurb/bokChoy.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e54"
}, {
    "name": "Broccoli",
    "description": "Broccoli",
    "category": "vegetables",
    "unitPrice": "2.49",
    "unitQuantity": "1",
    "unit": "ct",
    "imgUrl": "https://storage.googleapis.com/atkurb/broccoli.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e55"
}, {
    "name": "Brussel Sprouts",
    "description": "Brussel Sprouts",
    "category": "vegetables",
    "unitPrice": "3.49",
    "unitQuantity": "1",
    "unit": "lb",
    "imgUrl": "https://storage.googleapis.com/atkurb/brusselSprouts.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e56"
}, {
    "name": "Cabbage",
    "description": "Cabbage",
    "category": "vegetables",
    "unitPrice": "2.49",
    "unitQuantity": "1",
    "unit": "ct",
    "imgUrl": "https://storage.googleapis.com/atkurb/cabbage.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e57"
}, {
    "name": "Cactus Pear",
    "description": "Cactus Pear",
    "category": "vegetables",
    "unitPrice": "4.49",
    "unitQuantity": "1",
    "unit": "lb",
    "imgUrl": "https://storage.googleapis.com/atkurb/cactusPear.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e58"
}, {
    "name": "Cantaloupe",
    "description": "Cantaloupe",
    "category": "fruits",
    "unitPrice": "3.49",
    "unitQuantity": "1",
    "unit": "ct",
    "imgUrl": "https://storage.googleapis.com/atkurb/cantaloupe.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e59"
}, {
    "name": "Carrots",
    "description": "Carrots",
    "category": "vegetables",
    "unitPrice": "2.99",
    "unitQuantity": "1",
    "unit": "lb",
    "imgUrl": "https://storage.googleapis.com/atkurb/carrots.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e5a"
}, {
    "name": "Cauliflower",
    "description": "Cauliflower",
    "category": "vegetables",
    "unitPrice": "3.99",
    "unitQuantity": "1",
    "unit": "ct",
    "imgUrl": "https://storage.googleapis.com/atkurb/cauliflower.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e5b"
}, {
    "name": "Celery",
    "description": "Celery",
    "category": "vegetables",
    "unitPrice": "2.99",
    "unitQuantity": "1",
    "unit": "lb",
    "imgUrl": "https://storage.googleapis.com/atkurb/celery.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e5c"
}, {
    "name": "Cherries",
    "description": "Cherries",
    "category": "fruits",
    "unitPrice": "3.99",
    "unitQuantity": "1",
    "unit": "lb",
    "imgUrl": "https://storage.googleapis.com/atkurb/cherries.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e5d"
}, {
    "name": "Coconut",
    "description": "Coconut",
    "category": "fruits",
    "unitPrice": "2.99",
    "unitQuantity": "1",
    "unit": "ct",
    "imgUrl": "https://storage.googleapis.com/atkurb/coconut.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e5e"
}, {
    "name": "Collard Greens",
    "description": "Collard Greens",
    "category": "vegetables",
    "unitPrice": "3.99",
    "unitQuantity": "1",
    "unit": "lb",
    "imgUrl": "https://storage.googleapis.com/atkurb/collardGreens.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e5f"
}, {
    "name": "Corn",
    "description": "Corn",
    "category": "vegetables",
    "unitPrice": "2.99",
    "unitQuantity": "1",
    "unit": "lb",
    "imgUrl": "https://storage.googleapis.com/atkurb/corn.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e60"
}, {
    "name": "Cranberries",
    "description": "Cranberries",
    "category": "fruits",
    "unitPrice": "1.99",
    "unitQuantity": "1",
    "unit": "lb",
    "imgUrl": "https://storage.googleapis.com/atkurb/cranberries.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e61"
}, {
    "name": "Cucumbers",
    "description": "Cucumbers",
    "category": "vegetables",
    "unitPrice": "1.99",
    "unitQuantity": "1",
    "unit": "lb",
    "imgUrl": "https://storage.googleapis.com/atkurb/cucumbers.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e62"
}, {
    "name": "Dates",
    "description": "Dates",
    "category": "fruits",
    "unitPrice": "2.49",
    "unitQuantity": "1",
    "unit": "lb",
    "imgUrl": "https://storage.googleapis.com/atkurb/dates.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e63"
}, {
    "name": "Eggplant",
    "description": "Eggplant",
    "category": "vegetables",
    "unitPrice": "3.49",
    "unitQuantity": "1",
    "unit": "lb",
    "imgUrl": "https://storage.googleapis.com/atkurb/eggplant.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e64"
}, {
    "name": "Garlic",
    "description": "Garlic",
    "category": "vegetables",
    "unitPrice": "1.49",
    "unitQuantity": "1",
    "unit": "lb",
    "imgUrl": "https://storage.googleapis.com/atkurb/garlic.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e65"
}, {
    "name": "Gooseberries",
    "description": "Gooseberries",
    "category": "fruits",
    "unitPrice": "2.49",
    "unitQuantity": "1",
    "unit": "lb",
    "imgUrl": "https://storage.googleapis.com/atkurb/gooseberries.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e66"
}, {
    "name": "Grapefruit",
    "description": "Grapefruit",
    "category": "fruits",
    "unitPrice": "1.49",
    "unitQuantity": "1",
    "unit": "lb",
    "imgUrl": "https://storage.googleapis.com/atkurb/grapefruit.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e67"
}, {
    "name": "Grapes",
    "description": "Grapes",
    "category": "fruits",
    "unitPrice": "2.49",
    "unitQuantity": "1",
    "unit": "lb",
    "imgUrl": "https://storage.googleapis.com/atkurb/grapes.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e68"
}, {
    "name": "Green Beans",
    "description": "Green Beans",
    "category": "vegetables",
    "unitPrice": "3.49",
    "unitQuantity": "1",
    "unit": "lb",
    "imgUrl": "https://storage.googleapis.com/atkurb/greenBeans.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e69"
}, {
    "name": "Green Bell Peppers",
    "description": "Green Bell Peppers",
    "category": "vegetables",
    "unitPrice": "2.49",
    "unitQuantity": "1",
    "unit": "lb",
    "imgUrl": "https://storage.googleapis.com/atkurb/greenBellPeppers.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e6a"
}, {
    "name": "Green Chillis",
    "description": "Green Chillis",
    "category": "vegetables",
    "unitPrice": "2.49",
    "unitQuantity": "1",
    "unit": "lb",
    "imgUrl": "https://storage.googleapis.com/atkurb/greenChillis.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e6b"
}, {
    "name": "Green Peas",
    "description": "Green Peas",
    "category": "vegetables",
    "unitPrice": "2.49",
    "unitQuantity": "1",
    "unit": "lb",
    "imgUrl": "https://storage.googleapis.com/atkurb/greenPeas.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e6c"
}, {
    "name": "Guava",
    "description": "Guava",
    "category": "fruits",
    "unitPrice": "3.49",
    "unitQuantity": "1",
    "unit": "lb",
    "imgUrl": "https://storage.googleapis.com/atkurb/guava.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e6d"
}, {
    "name": "Iceberg Lettuce",
    "description": "Iceberg Lettuce",
    "category": "vegetables",
    "unitPrice": "1.49",
    "unitQuantity": "1",
    "unit": "ct",
    "imgUrl": "https://storage.googleapis.com/atkurb/icebergLettuce.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e6e"
}, {
    "name": "Kale",
    "description": "Kale",
    "category": "vegetables",
    "unitPrice": "2.49",
    "unitQuantity": "1",
    "unit": "lb",
    "imgUrl": "https://storage.googleapis.com/atkurb/kale.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e6f"
}, {
    "name": "Kiwifruit",
    "description": "Kiwifruit",
    "category": "fruits",
    "unitPrice": "1.49",
    "unitQuantity": "1",
    "unit": "lb",
    "imgUrl": "https://storage.googleapis.com/atkurb/kiwifruit.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e70"
}, {
    "name": "Lemons",
    "description": "Lemons",
    "category": "fruits",
    "unitPrice": "3.49",
    "unitQuantity": "1",
    "unit": "lb",
    "imgUrl": "https://storage.googleapis.com/atkurb/lemons.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e71"
}, {
    "name": "Limes",
    "description": "Limes",
    "category": "fruits",
    "unitPrice": "2.49",
    "unitQuantity": "1",
    "unit": "lb",
    "imgUrl": "https://storage.googleapis.com/atkurb/limes.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e72"
}, {
    "name": "Lychee",
    "description": "Lychee",
    "category": "fruits",
    "unitPrice": "1.49",
    "unitQuantity": "1",
    "unit": "lb",
    "imgUrl": "https://storage.googleapis.com/atkurb/lychee.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e73"
}, {
    "name": "Madarins",
    "description": "Madarins",
    "category": "fruits",
    "unitPrice": "2.49",
    "unitQuantity": "12",
    "unit": "ct",
    "imgUrl": "https://storage.googleapis.com/atkurb/madarins.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e74"
}, {
    "name": "Mango",
    "description": "Mango",
    "category": "fruits",
    "unitPrice": "1.49",
    "unitQuantity": "1",
    "unit": "lb",
    "imgUrl": "https://storage.googleapis.com/atkurb/mango.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e75"
}, {
    "name": "Mushrooms",
    "description": "Mushrooms",
    "category": "others",
    "unitPrice": "1.49",
    "unitQuantity": "1",
    "unit": "lb",
    "imgUrl": "https://storage.googleapis.com/atkurb/mushrooms.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e76"
}, {
    "name": "Okra",
    "description": "Okra",
    "category": "vegetables",
    "unitPrice": "2.49",
    "unitQuantity": "1",
    "unit": "lb",
    "imgUrl": "https://storage.googleapis.com/atkurb/okra.png",
    "stockSize": "100",
    "productDateStoreId": "5ecdaad696ff000e752d8e77"
}]
