export const ADD = "ADD";
export const AUTHENTICATE_CUSTOMER = "AUTHENTICATE_CUSTOMER";
export const AUTHENTICATE_STORE = "AUTHENTICATE_STORE";
export const DENY_AUTHENTICATION_STORE = "DENY_AUTHENTICATION_STORE";
export const DENY_AUTHENTICATION_CUSTOMER = "DENY_AUTHENTICATION_CUSTOMER";
